config/routes.rb
Rails.application.routes.draw do
  resources :carros
  
  get '/estados', to: 'estados#index'
  get '/cidades', to: 'estados#cidades'
  get '/', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carro.rb
class Carro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /carros or /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1 or /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros or /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to carro_url(@carro), notice: "Carro was successfully created." }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1 or /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to carro_url(@carro), notice: "Carro was successfully updated." }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1 or /carros/1.json
  def destroy
    @carro.destroy

    respond_to do |format|
      format.html { redirect_to carros_url, notice: "Carro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carro_params
      params.require(:carro).permit(:nome, :marca, :modelo, :ano)
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  def index

    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept'

    estados = [
      {nome: "São Paulo", uf: "SP"},
      {nome: "Rio de Janeiro", uf: "RJ"},
      {nome: "Minas Gerais", uf: "MG"},
      {nome: "Goiás", uf: "GO"},
      {nome: "Espirito Santo", uf: "ES"},
    ] 

    if params["uf"].present?
      estados = estados.select{ |e| e[:uf].upcase == params["uf"].upcase}
    end

    render json: estados, status: 200
  end

  def cidades

    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept'


    cidades = [
      {nome: "São Paulo", uf: "SP"},
      {nome: "Santo André", uf: "SP"},
      {nome: "Maua", uf: "SP"},
      {nome: "Campinas", uf: "SP"},
      {nome: "Rio de Janeiro", uf: "RJ"},
      {nome: "Cabo Frio", uf: "RJ"},
      {nome: "Niteroi", uf: "RJ"},
    ]

    if params["uf"].present?
      cidades = cidades.select{ |e| e[:uf].upcase == params["uf"].upcase}
    end

    render json: cidades, status: 200
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_carro.html.erb
<div id="<%= dom_id carro %>">
  <p>
    <strong>Nome:</strong>
    <%= carro.nome %>
  </p>

  <p>
    <strong>Marca:</strong>
    <%= carro.marca %>
  </p>

  <p>
    <strong>Modelo:</strong>
    <%= carro.modelo %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= carro.ano %>
  </p>

</div>

app/views/carros/_form.html.erb
<%= form_with(model: carro) do |form| %>
  <% if carro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
        <% carro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :marca, style: "display: block" %>
    <%= form.text_field :marca %>
  </div>

  <div>
    <%= form.label :modelo, style: "display: block" %>
    <%= form.text_field :modelo %>
  </div>

  <div>
    <%= form.label :ano, style: "display: block" %>
    <%= form.number_field :ano %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render "form", carro: @carro %>

<br>

<div>
  <%= link_to "Show this carro", @carro %> |
  <%= link_to "Back to carros", carros_path %>
</div>

app/views/carros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carros</h1>

<div id="carros">
  <% @carros.each do |carro| %>
    <%= render carro %>
    <p>
      <%= link_to "Show this carro", carro %>
    </p>
  <% end %>
</div>

<%= link_to "New carro", new_carro_path %>

app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render "form", carro: @carro %>

<br>

<div>
  <%= link_to "Back to carros", carros_path %>
</div>

app/views/carros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @carro %>

<div>
  <%= link_to "Edit this carro", edit_carro_path(@carro) %> |
  <%= link_to "Back to carros", carros_path %>

  <%= button_to "Destroy this carro", @carro, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>API Estados aula</h1>

<a href="http://127.0.0.1:3000/estados.json">Estados</a><br>
<a href="http://127.0.0.1:3000/cidades.json">Cidades</a><br>
<a href="http://127.0.0.1:3000/cidades.json?uf=sp">Cidades SP</a><br>

<div style="margin-top: 30px">
  <h5>Estados</h5>
  <select onChange="loadCidades(this.value)"id="estados">
    <option>Selecione</option>
  </select>
</div>

<div style="margin-top: 30px">
  <h5>Cidades</h5>
  <select id="cidades">
    <option>Selecione</option>
  </select>
</div>

<h1>Lista de Carros</h1>
<fieldset id="formCars">
    <legend>Carro:</legend>
    Nome: <input type="text" id="nome"><br>
    Marca: <input type="text" id="marca"><br>
    Modelo: <input type="text" id="modelo"><br>
    Ano: <input type="text" id="ano"><br>
    <button onClick="SaveForm()">Submit</button>
  </fieldset>
<br>

<table class="table" id="tableCars">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Ano</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
    </tr>
  </tbody>
</table>


<script type="text/javascript" src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script type="text/javascript" >
  var loadEstados = function(){
    $.ajax({
      url: "http://127.0.0.1:3000/estados.json",
      context: document.body
    }).done(function(dados) {
      $("#estados").html("<option>Selecione</option>")
      $(dados).each(function(){
        $("#estados").append("<option value='" + this.uf + "'>" + this.nome + "</option>")
      });
    });
  }

  var loadCidades = function(uf){
    $.ajax({
      url: "http://127.0.0.1:3000/cidades.json?uf="+ uf,
      context: document.body
    }).done(function(dados) {

      $("#cidades").html("<option>Selecione</option>")
      $(dados).each(function(){
        $("#cidades").append("<option>" + this.nome + "</option>")
      });
    });
  }

  loadEstados();

  var loadCars = function(){
    $("#tableCars tbody").html("");
    $.ajax({
      url: "http://127.0.0.1:3000/carros.json",
      context: document.body
    }).done(function(cars) {
      $(cars).each(function(){
        $("#tableCars tbody").append("<tr data-id='"+ this.id +"'><td ondblclick='changeLine(this)' data-nome='nome'>" + this.nome +"</td><td ondblclick='changeLine(this)' data-nome='marca'>" + this.marca + "</td><td ondblclick='changeLine(this)' data-nome='modelo'>" + this.modelo + "</td><td ondblclick='changeLine(this)' data-nome='ano'>" + this.ano + "</td><td data-nome='apagar'><a href=\"javascript:apagar(\' " + this.id + " \')\">Apagar</a></td></tr>")
      });
    });
  }

  loadCars();

  var changeLine = function(self){
    $(self).each(function(){
      var conteudo = $(this).text();
      if($(this).data("nome") != "apagar"){
        $(this).html("<input type='text' onblur='save(this)' name='"+ $(this).data("nome") +"' value='"+ conteudo +"' >");
      }
    });
  }

  var save = function(self){
    var carroId = $(self).parents("tr").data("id")
    var campo = $(self).attr("name")

    var carro = {}
    carro[campo] = $(self).val()

    $.ajax({
      type: 'PUT',
      url: "http://127.0.0.1:3000/carros/"+ carroId +".json", 
      data: {
        carro: carro
      }
    }).done(function(cars) {
      $(self).parents("td").html($(self).val())
      })
      .fail(function() {
        alert("Erro ao atualizar campo");
      });
  }

  var SaveForm = function(){
    var dados = {
      carro: {
        nome: $("#nome").val(),
        marca: $("#marca").val(),
        modelo: $("#modelo").val(),
        ano: $("#ano").val()
    }
  };
  $.post("http://127.0.0.1:3000/carros.json", dados)
    .done(function(cars) {
      $("#nome").val("");
      $("#marca").val("");
      $("#modelo").val("");
      $("#ano").val("");
      loadCars();
    })
    .fail(function() {
      alert("Erro ao cadastrar");
    });
  }

  var apagar = function(carroId){
    $.ajax({
      type: 'DELETE',
      url: "http://127.0.0.1:3000/carros/"+ carroId +".json", 
    }).done(function(cars) {
        loadCars();
      })
      .fail(function() {
        alert("Erro ao deletar");
      });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>